"""
SentinelX EDR - Alert Model
============================
Represents a detected threat/alert generated by the detection engine.

Alert lifecycle:
    1. Detection engine fires → Alert created (status="open")
    2. AI investigation triggered → status="investigating"
    3. Analyst reviews → status="acknowledged"
    4. Case created / resolved → status="resolved" or "false_positive"
    5. Case closed → status="closed"
"""

from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, DateTime, Text, Float, ForeignKey
from app.database import Base


class Alert(Base):
    """
    A security alert generated by the threat detection engine.
    
    Alerts are created when:
        - A Sigma rule matches telemetry data
        - An IOC (hash, IP, domain) is found in telemetry
        - A behavioral detector identifies suspicious activity
        - A plugin detector fires
    """
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    endpoint_id = Column(String(36), ForeignKey("endpoints.id"), nullable=False, index=True)

    # Alert details
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=True)
    severity = Column(String(20), nullable=False, index=True)  # critical, high, medium, low, info
    status = Column(String(20), nullable=False, default="open", index=True)
    # Status values: open, investigating, acknowledged, resolved, false_positive, closed

    # Detection source
    rule_name = Column(String(255), nullable=True)
    rule_type = Column(String(50), nullable=True)  # sigma, ioc, behavioral, plugin
    rule_id = Column(String(100), nullable=True)

    # MITRE ATT&CK mapping (from rule tags or AI investigation)
    mitre_tactic = Column(String(100), nullable=True)  # e.g., "Execution"
    mitre_technique = Column(String(20), nullable=True)  # e.g., "T1059.001"
    mitre_technique_name = Column(String(255), nullable=True)  # e.g., "PowerShell"

    # Evidence (JSON-serialized dict with matched event data)
    evidence = Column(Text, nullable=True)  # JSON string

    # Metrics
    detection_latency_ms = Column(Float, nullable=True)  # Time from event to alert

    # Timestamps
    detected_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
        index=True,
    )
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)

    def __repr__(self) -> str:
        return f"<Alert [{self.severity}] {self.title} ({self.status})>"
