"""Initial schema

Revision ID: fc51b6f00db8
Revises: 
Create Date: 2026-06-26 09:38:28.769223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc51b6f00db8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hunt_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=True),
    sa.Column('query_payload', sa.JSON(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hunt_history_id'), 'hunt_history', ['id'], unique=False)
    op.create_table('response_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('action_requested', sa.String(), nullable=True),
    sa.Column('execution_mode', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_logs_endpoint_id'), 'response_logs', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_response_logs_id'), 'response_logs', ['id'], unique=False)
    op.create_table('saved_hunts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('query_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_hunts_id'), 'saved_hunts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_hunts_id'), table_name='saved_hunts')
    op.drop_table('saved_hunts')
    op.drop_index(op.f('ix_response_logs_id'), table_name='response_logs')
    op.drop_index(op.f('ix_response_logs_endpoint_id'), table_name='response_logs')
    op.drop_table('response_logs')
    op.drop_index(op.f('ix_hunt_history_id'), table_name='hunt_history')
    op.drop_table('hunt_history')
    # ### end Alembic commands ###
